### ISSUE TITLE
Finalize the input format 

### ISSUE THREAD

**Issue by chameerawijebandara** [chameerawijebandara/Satellite-Image-Analyzer-#1]
- Identify best Image format
- finalize resolution(fix) (like 1cm = 1km)

**Comment by HBMDDS** [comment]
Couldn't find a way to set a fix zoom value by number. It can just zoom by mouse and can't set the resolution as we want. Resolution changes automatically to some value

**Comment by chameerawijebandara** [comment]
Some how we need to come up with a solution

**Comment by HBMDDS** [comment]
Figured a way to save images. I think it will be better to save of scale, 1 pixel = 1 meter

**Comment by HBMDDS** [comment]
Also finished the code to crop samples of trees from images. We can click on a point on the image and small box (8x8) will be drawn around that point. Then if we want we can save that 8x8 image by right clicking.

**Comment by chameerawijebandara** [comment]
Greate
one thing to note.
When you adding a commits in github issues, please use the corresponding
issue.

**Comment by chameerawijebandara** [comment]
Can you please document the posses to save image in particular format. 
Simple description with screen capture is sufficient

**Comment by HBMDDS** [comment]
Forgot to mention that I saved images in .jpg format.

**Comment by chameerawijebandara** [comment]
(Y)

**Comment by HBMDDS** [comment]
There's no need to document the process of saving the image. We just have to open the image in that software and save with default values (1 pixel = 1 meter is the default) in jpg format

**Comment by chameerawijebandara** [comment]
Fine let's proceed that way

**Comment by chameerawijebandara** [comment]
Hope this is issue can close now
